name: 'Get Status'
description: 'Get the status checks of a given ref.'
inputs:
  ref:
    description: 'Git ref, e.g. the sha.'
    required: true
  token:
    description: 'The GitHub token used to create an authenticated client.'
    default: ${{ github.token }}
    required: false
  ignore:
    description: 'Workflow names that will be ignored during the validation. For multiple values, please separate them with commas, e.g. "test,build,get-status"'
    required: false
outputs:
  all-checks-completed:
    description: 'Returns true if all checks are completed.'
  all-checks-passed:
    description: 'Returns true if all checks concluded either with success or skipped.'
runs:
  using: 'node16'
  main: 'dist/index.js'
