name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Status of current ref
        id: get-status
        uses: ./
        with:
          ref: ${{ github.sha }}
          token: ${{ github.token }}
      - name: Only executes if all checks passed
        if: ${{steps.get-status.outputs.all-checks-completed == 'false' &&  steps.get-status.outputs.all-checks-passed == 'true'}}
        run: echo "Test successful"
